version: '3.8'

services:
  psostats:
    image: golang:1.18
    container_name: psostats
    command: bash -c "cd /app && go mod download && go run server/cmd/main.go"
    networks:
      - main
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      WEBHOOK_URL: ${WEBHOOK_URL}
    volumes:
      - ".:/app"
      - /dev/null:/app/.env
    restart: unless-stopped
networks:
  main:
    name: main
