version: '3.8'

services:
  psostats:
    image: psostats
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: psostats
    command: go run /app/server/cmd/main.go
    networks:
      - main
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    restart: unless-stopped
networks:
  main:
    name: main
